### ISSUE TITLE
Working AST -> Interpreter pipeline for xy plotter example

### ISSUE THREAD

**Issue by jtranoleary** [machineagency/machine-o-matic#9]
Finish implementing the solver to take a handmade AST and return a working interpreter.

*[Jasper will handle this. There are a lot more details here but he knows them in his head.]*

**Comment by jhaazpr** [comment]
jhaazpr@9a1f765f6199c5b44bc14c690258564f50335f77

**Comment by jhaazpr** [comment]
https://github.com/machineagency/machine-o-matic/commit/9a1f765f6199c5b44bc14c690258564f50335f77
